---
 - name: Traefik Ingress Setup Play
   hosts: kmaster
   gather_facts: false
   
   tasks:
     - name: checking Helm tool is installed or not
       shell: whereis helm | egrep -o "/usr/local/bin/helm|/usr/bin/helm"
       register: out
       failed_when: false
       changed_when: false
     
     - name: Installing Helm tool
       shell: |
               yum install wget -y
               wget https://get.helm.sh/helm-v3.6.2-linux-amd64.tar.gz
               tar -zxf helm-v3.6.2-linux-amd64.tar.gz
               mv linux-amd64/helm /usr/local/bin/
       when: "'helm' not in out.stdout"
  
     - debug:
         msg: Already Helm tool is installed
       when: "'helm' in out.stdout"

     - name: Creating new namespace for Traefik Ingress
       command: kubectl create ns traefik-ingress
      
     - name: Adding Traefik Ingress repo and updating helm repo
       shell: |
               helm repo add traefik https://helm.traefik.io/traefik
               helm repo update
     
     - name: Installing Traefik Ingress Controller
       shell: |
               helm install traefik-ingress traefik/traefik -n traefik-ingress > /tmp/traefik-ingress.outs

     - name: Setup Traefik Dashboard with LoadBalancer Service
       shell: |
               kubectl apply -f https://raw.githubusercontent.com/avi1512/Traefik-Dashboard-SVC/main/traefik-dashboard-svc.yml -n traefik-ingress

     - name: Verify Installation
       shell: |
               helm list --all-namespaces
       register: outs
     - debug: var=outs.stdout_lines
